[package]
name = "rschain"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
rand = "0.8.5"
ripemd = "0.1.3"
secp256k1 = { version = "0.30.0", features = ["rand", "hashes"] }
sha2 = "0.10.8"
